### ISSUE TITLE
Generators chapter typo

### ISSUE THREAD

**Issue by lancelote** [yasoob/intermediatePython#117]
Pull request #105 by @DavidAwad introduced to the [generators chapter](https://github.com/yasoob/intermediatePython/blob/master/generators.rst) this phrase:

> While an ``int`` isn't an iterable, we can use it on string!

Is it a typo or I just cannot grasp the meaning?

Thanks in advance for any clarification!

**Comment by yasoob** [comment]
It is not a typo. I have updated the chapter to include an example involving `int`. I am not sure what clarification I can give. [This answer](http://stackoverflow.com/questions/19523563/python-typeerror-int-object-is-not-iterable) might make it a bit more clear for you. If there is anything specific which I can help you with then just let me know.

**Comment by yasoob** [comment]
I am closing this for now but you can reopen it if you want any more clarifications.
