### ISSUE TITLE
Ternary Operators

### ISSUE THREAD

**Issue by mobedigg** [yasoob/intermediatePython#121]
> This works simply because True == 1 and False == 0,

I think it's not fully correct for Python 2.x, because you can change value for True and False there.
This was changed in Python 3.x
https://wiki.python.org/moin/Python3.0

> Make True and False keywords. [6]
> 
>     Reason: make assignment to them impossible.

**Comment by lancelote** [comment]
You are right of course, but who the hell will reasign True or False?! =D
Anyway, this level of details can be skipped for the tutorial I think. As the author said in [README](https://github.com/yasoob/intermediatePython/blob/master/README.md):

> Please note that this book is not a tutorial and does not teach you Python. The topics are not explained in-depth and only the minimum required information is given.

**Comment by yasoob** [comment]
Hey @mobedigg I am talking about the default behavior over here. Otherwise you can even do this in Python 2 and Python 3:

```
int = 31
str = "Not this function is a variable"
```

I hope this makes things a bit more clear. :smile:
