### ISSUE TITLE
Parallel sorting technique using lambda's gives an incorrect result

### ISSUE THREAD

**Issue by pitai** [yasoob/intermediatePython#135]
I don't completely understand the zip functionality/sorting of tuples, but when I do

```
list1 = [1,2,3,4,2,1]
list2 = [6,7,8,7,6,5]
data = zip(list1, list2)
data.sort()
print data
list1, list2 = map(lambda t: list(t), zip(*data))
print "----"
print list1
print list2
```

It produces the result:

```
[(1, 5), (1, 6), (2, 6), (2, 7), (3, 8), (4, 7)]
----
[1, 1, 2, 2, 3, 4]
[5, 6, 6, 7, 8, 7]
```

Here as 7 is before 8. This particular strategy is given in the lambda section

**Comment by jay3zhang** [comment]
the code is meaning : The elements of list2 will be sorted according to the element size of list1 in the corresponding index. 
For your example, the last 7(in list2) corresponds to 4(in list1)，8 corresponds to 3，so 8 before the last 7.

**Comment by yasoob** [comment]
Kindly refer to what @jay3zhang said. If there is still any problem feel free to comment and I will reopen the issue.

**Comment by govindrai** [comment]
I found this last example to be more confusing than helpful. Parallel sorting of lists intuitively implies that both lists would be sorted somehow. However that is not the case (atleast at face value). Maybe you want to add @jay3zhang's comment to the example.
