### ISSUE TITLE
9.Mutation Typo found 

### ISSUE THREAD

**Issue by Payuing** [yasoob/intermediatePython#146]
Second example
````python
foo = ['hi']
print(foo)
# Output: ['hi']

bar = foo
bar += ['bye']

print(foo)
# Output: ['hi'] 
***#THE OUTPUT HERE SHOULD BE ['hi', 'bye']***

print(bar)
# Output: ['hi', 'bye']
````

**Comment by lancelote** [comment]
Hi @Payuing ! It's an intentionally wrong example to illustrate the wrong intuition one can have there, check the text above the code:

>We were expecting something like this:
