### ISSUE TITLE
Context manager exit function return

### ISSUE THREAD

**Issue by abhigenie92** [yasoob/intermediatePython#150]
```
class File(object):
    def __init__(self, file_name, method):
        self.file_obj = open(file_name, method) def __enter__(self):
    def __enter__(self):
        return self.file_obj
    def __exit__(self, type, value, traceback):
        self.file_obj.close()
```

For this code even though, the exit may close the file correctly , shouldn't it raise an error with the `with` statement anyways. Because it is not returning anything. And will return None therefore.
In the chapter, it is mentioned that only when exit() returns True, an exception won't be raised.

**Comment by habnabit** [comment]
`with` statements reraising is common and expected behavior, yes.

**Comment by abhigenie92** [comment]
@habnabit thanks for the reply.
Just to make the question more clear.
In this chapter, https://github.com/yasoob/intermediatePython/blob/master/context_managers.rst#implementing-context-manager-as-a-class, the example includes exit not returning anything. Still no exception is raised.

**Comment by habnabit** [comment]
https://repl.it/KLNe/0 here, you can see the file object is closed and the exception is reraised.

**Comment by abhigenie92** [comment]
If I comment out `#raise RuntimeError('exception')`. There is no exception raised. But the exit function has no return statement.

**Comment by habnabit** [comment]
Yes. If no exception has been raised, there's nothing to _reraise_. In that case, nothing happens.

**Comment by abhigenie92** [comment]
Shouldn't an exception be raised it the exit function didn't return `True`. As in this case, the exit function has no return statement. So I assuming it return `None`.

**Comment by habnabit** [comment]
>Shouldn't an exception be raised it the exit function didn't return `True`.

What exception would be raised?

>As in this case, the exit function has no return statement. So I assuming it return `None`.

Correct. But even without returning `True`, nothing happens, as there is nothing to reraise.

**Comment by abhigenie92** [comment]
So do you mean, an exception is raised only when the exit function was initially passed with `type, value, traceback` and it doesn't `True`? Implying that it didn't handle the exception.

Assuming above is `True`, how does the exit function behave when no exception is raised in the first place? Does the return of exit matter in that case?

**Comment by habnabit** [comment]
>[H]ow does the exit function behave when no exception is raised in the first place?

`type is value is traceback is None`

>Does the return of exit() matter in that case?

Assuming you mean `__exit__`, this is what I've been trying to say: no, it doesn't matter. The return value of `__exit__` is only considered if an exception was raised in the `with` block.
