### ISSUE TITLE
Correct default dict example

### ISSUE THREAD

**Issue by nanjekyejoannah** [yasoob/intermediatePython#174]
In this example under defaultdict.
``
from collections import defaultdict

colours = (
    ('Yasoob', 'Yellow'),
    ('Ali', 'Blue'),
    ('Arham', 'Green'),
    ('Ali', 'Black'),
    ('Yasoob', 'Red'),
    ('Ahmed', 'Silver'),
)

favourite_colours = defaultdict(list)

for name, colour in colours:
    favourite_colours[name].append(colour)

print(favourite_colours)

# output
# defaultdict(<type 'list'>,
#    {'Arham': ['Green'],
#     'Yasoob': ['Yellow', 'Red'],
#     'Ahmed': ['Silver'],
#     'Ali': ['Blue', 'Black']
# })
``
We should append colours not colour.

**Comment by lancelote** [comment]
Try to change the code to see what will happen. The original example is correct - for each person we append his favorite colour to the list. There's a little sense to append the whole data set over an over again.
