### ISSUE TITLE
Good job and keep writing!

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [yasoob/intermediatePython#204]
Hi there!

Just stumbled across the book and wanted to say - nicely done! Thank you for it, bookmarked the book site, this repo and your blog. :-)

Good luck out there and feel free to close this! 

Have a :token-of-appreciation:! :100: :-)

Of course, while the above is mainly for @yasoob I still am thankful to all the others who have put in their work and made it happen. Thank you guys as well!

**Comment by yasoob** [comment]
Hi! Thank you so much :)
