### ISSUE TITLE
for else

### ISSUE THREAD

**Issue by madhaven** [yasoob/intermediatePython#215]
```
for some condition:
    ;lkasdj;flk
else:
    ;alksdflkj
```
and 

```
for some condition:
    ;alksdjf
;alskdfj
```

works the same don't it

**Comment by theriverman** [comment]
They work differently. If you put a break statement into your first example, the `else` clause will not be executed. 

BR,
/Kristof

**Comment by yasoob** [comment]
@theriverman is correct. @madhaven I am going to close this issue for now but if you have any more questions feel free to open it again :)
