### ISSUE TITLE
[Collections.namedtuple] Tuples also store references to other objects.

### ISSUE THREAD

**Issue by YoungxHelsinki** [yasoob/intermediatePython#38]
In [namedtuple](http://book.pythontips.com/en/latest/collections.html#namedtuple), you wrote:
*"A tuple is a lightweight object type which allows to store a sequence of immutable Python objects."*
That is not quite right. In fact, a tuple doesn't contain objects, it only contains references. Therefore a tuple can also contain a reference to a list:

```python
a = ('sam_favorite_fruit', ['apple', 'pineapple'])
```

For further explanation, please refer [this](http://stackoverflow.com/a/9756041/3067013)

**Comment by StevenMaude** [comment]
Also in that same section:

> you can not change a value in a tuple

That might be confusing wording. It's true that you can't modify the tuple so that you change which objects one of its elements directly refers to. But, those objects don't suddenly become immutable because they are in a tuple:

```python
>>> a = [1, 2]
>>> b = (3, a)
>>> b
(3, [1, 2])
>>> b[1] = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object does not support item assignment
>>> b[1][1] = 4
>>> b
(3, [1, 4])
```

**Comment by YoungxHelsinki** [comment]
As the error message says, `TypeError: 'tuple' object does not support item assignment`, 
>you can not change a value in a tuple

could be updated to
>you can not reassign an item in a tuple

Human vocabularies such as "modify", "change" or "edit" is not suitable for explaining data types.

**Comment by yasoob** [comment]
Thanks for pointing it out! Perhaps you can send a PR? :+1: 

If not then let me know and I can work on it!

**Comment by YoungxHelsinki** [comment]
PR stands for Push Request?

**Comment by yasoob** [comment]
It stands for Pull Request :)
