### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [yasoob/intermediatePython#61]
What license is this book under?

**Comment by yasoob** [comment]
It is released under "Attribution-NonCommercial-ShareAlike CC BY-NC-SA". It is basically a Creative Commons license. I am not a license fanatic so in simple words:

> This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms. 

I will mention it in the README and the index page. Thanks for bringing this up!
