### ISSUE TITLE
7.5 Decorator

### ISSUE THREAD

**Issue by angoodkind** [yasoob/intermediatePython#66]
It is confusing to name the new function variable the same thing as the existing function, i.e.:
```python
a_function_requiring_decoration = a_new_decorator(a_function_requiring_decoration)
```
Why not just:
```python
x = a_new_decorator(a_function_requiring_decoration)
```
When I tried the code in the first section in an python notebook, I got:
```python
I am doing some boring work before executing a_func()
I am doing some boring work before executing a_func()
I am the function which needs some decoration to remove my foul smell
I am doing some boring work after executing a_func()
I am doing some boring work after executing a_func()
```
However, it worked in IDLE. Any idea why?

**Comment by lancelote** [comment]
@angoodkind I believe you just accidentally executed
```
a_function_requiring_decoration = a_new_decorator(a_function_requiring_decoration)
```
two times (pretty easy with IPython notebook), so you decorated already decorated function = ) Then the output is understandable.

**Comment by yasoob** [comment]
You are absolutely correct @lancelote. @angoodkind I am going to close this issue for now. If anything is still unclear then we can open it again.

Cheers! :smile:
