### ISSUE TITLE
A potential typo and missing link (or misplaced text)

### ISSUE THREAD

**Issue by hassanzaheer123** [yasoob/intermediatePython#94]
On this link under the "Iterable" heading, there is this line: "(Both of these dunder methods are fully explained in a previous chapter)". Here I think 'dunder' is obviously a typo and this link is perhaps either copy/pasted from somewhere else or misplaced because there isn't any previous chapter that focuses on these two topics.

**Comment by yasoob** [comment]
dunder methods are those methods which contain double underscore :) ```__``` I would make sure to highlight the definition more clearly.
